name: "score_download"
description: Overture SCORE clients for downloading of files and metadata.
keywords:
  - overture
  - score-client
  - download
tools:
  - "score":
      description: |
        Score facilitates the transfer and storage of your data seamlessly for cloud-based projects. 
        File bundling, resumable downloads, and BAM/CRAM slicing make data transfer fast and smooth.
      homepage: "https://www.overture.bio/products/score/"
      documentation: "https://score-docs.readthedocs.io/en/develop/index.html"
      tool_dev_url: "https://github.com/overture-stack/score"
      doi: ""
      licence: ["MIT"]

input:
  - analysis:
      type: file
      description: SONG metadata JSON file 
  - study_id:
      type: string
      description: SONG metadata study ID
  - analysis_id:
      type: string
      description: SONG metadata analysis ID

output:
  - analysis_json:
      type: file
      description: SONG metadata JSON file for downloaded files
  - files:
      type: file
      description: List of downloaded files
      pattern: "out/*"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@lespalex"
  - "@junjun-zhang"
  - "@lindaxiang"
  - "@edsu7"
