---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "tabix_tabix"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::tabix=1.11"
